const NOT_AUTHEN = 'NOT_AUTHEN' ;
const FAIL_VALIDATION='FAIL_VALIDATION';
const LOGIN_FAIL='LOGIN_FAIL';
const UPDATE_FAIL='LOGIN_FAIL';
const ERROR_PASSWORD='FAIL_CURENTPASSWORD';
module.exports = {
    NOT_AUTHEN,
    FAIL_VALIDATION ,
    LOGIN_FAIL,
    UPDATE_FAIL,
    ERROR_PASSWORD
}